### ISSUE TITLE
Error linking libraries

### ISSUE THREAD

**Issue by jmollink** [fordanic/openslide-matlab#2] opened 2015-11-05 16:36 UTC
Dear Daniel,

Thanks for matlab wrapper for Openslide. I followed your instructions for installing the package in matlab. Openslide was installed via brew with all the required dependencies on Mac OSX, Yosemite. When I try to run _openslide_load_library.m_  (in Matlab2015b), I get the following error. Any idea how to solve this? (btw, I have very little experience with C).

Error using loadlibrary
There was an error loading the library "/usr/local/opt/openslide/lib/libopenslide.0.dylib"
dlopen(/usr/local/opt/openslide/lib/libopenslide.0.dylib, 6): Library not loaded:
/usr/local/lib/libtiff.5.dylib
  Referenced from: /usr/local/opt/openslide/lib/libopenslide.0.dylib
  Reason: Incompatible library version: libopenslide.0.dylib requires version 8.0.0 or later,
  but libtiff.5.dylib provides version 6.0.0

Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...

Caused by:
    Error using loaddefinedlibrary
    dlopen(/usr/local/opt/openslide/lib/libopenslide.0.dylib, 6): Library not loaded:
    /usr/local/lib/libtiff.5.dylib
      Referenced from: /usr/local/opt/openslide/lib/libopenslide.0.dylib
      Reason: Incompatible library version: libopenslide.0.dylib requires version 8.0.0 or
      later, but libtiff.5.dylib provides version 6.0.0

**Comment by bgilbert** [comment] 2015-11-05 19:28
OpenSlide maintainer here.  Your OpenSlide library was linked with a particular version of libtiff, but the system is trying to load an older libtiff library instead.  Is `/usr/local/opt` your Homebrew installation?  Where did `/usr/local/lib/libtiff.5.dylib` come from?  Could you run `otool -L /usr/local/opt/openslide/lib/libopenslide.0.dylib` and post the output?

**Comment by jmollink** [comment] 2015-11-05 20:03
It could be coming from a previous installation of vips with brew? That's my guess. Now I'm seeing that brew installs the packages in `/usr/local/Cellar/`. Would it be better to do a clean install without brew but from source in `/usr/local/opt/`? Here's the output of your request.

```
otool -L /usr/local/opt/openslide/lib/libopenslide.0.dylib

/usr/local/opt/openslide/lib/libopenslide.0.dylib:
/usr/local/opt/openslide/lib/libopenslide.0.dylib (compatibility version 5.0.0, current version 5.1.0)
    /usr/local/lib/libgthread-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
    /usr/local/lib/libgio-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
    /usr/local/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.2.0)
    /usr/lib/libsqlite3.dylib (compatibility version 9.0.0, current version 168.2.0)
    /usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.2.0)
    /usr/local/lib/libopenjpeg.5.dylib (compatibility version 5.0.0, current version 1.5.2)
    /usr/local/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.2.0)
    /usr/local/lib/libpng16.16.dylib (compatibility version 35.0.0, current version 35.0.0)
    /usr/local/lib/libgdk_pixbuf-2.0.0.dylib (compatibility version 3001.0.0, current version 3001.8.0)
    /usr/local/lib/libgobject-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
    /usr/local/lib/libglib-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
    /usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by bgilbert** [comment] 2015-11-09 17:44
From [this documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#terminology---homebrew-speak), it appears that `/usr/local/lib` and `/usr/local/opt` both come from Homebrew, so I'm guessing the problem is elsewhere.  I saw a similar problem once before, which was caused by OpenSlide conflicting with a copy of libtiff shipped with Matlab itself.  There's no evidence of that in your error message, but maybe it's happening here too.  Let's get a dump of every copy of libtiff on your system:

``` shell
find / -name libtiff.*.dylib -print0 2>/dev/null | xargs -0 otool -L
```

**Comment by fordanic** [comment] 2015-11-12 19:03
Sorry for not noticing this issue earlier but it appears that appropriate help has already been given.

**Comment by jmollink** [comment] 2015-11-14 14:25
Sorry for the delay, here the output.

``````
/Applications/gedit.app/Contents/Resources/lib/libtiff.3.dylib:
        /Users/jesse/gtk/inst/lib/libtiff.3.dylib (compatibility version 12.0.0, current version 12.2.0)
        /Users/jesse/gtk/inst/lib/libjpeg.62.dylib (compatibility version 63.0.0, current version 63.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Applications/Gimp.app/Contents/Resources/lib/libtiff.3.dylib:
        /tmp/skl/Gimp.app/Contents/Resources/lib/libtiff.3.dylib (compatibility version 13.0.0, current version 13.2.0)
        /tmp/skl/Gimp.app/Contents/Resources/lib/libjpeg.62.dylib (compatibility version 63.0.0, current version 63.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/Applications/HistoloZee.app/Contents/Frameworks/libtiff.5.dylib:
        @executable_path/../Frameworks/libtiff.5.dylib (compatibility version 8.0.0, current version 8.0.0)
        @executable_path/../Frameworks/liblzma.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        @executable_path/../Frameworks/libjpeg.9.dylib (compatibility version 10.0.0, current version 10.0.0)
        @executable_path/../Frameworks/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/Applications/Inkscape.app/Contents/Resources/lib/libtiff.3.dylib (architecture ppc7400):
        @executable_path/../lib/libz.1.dylib (compatibility version 13.0.0, current version 13.5.0)
        @executable_path/../lib/libjpeg.8.dylib (compatibility version 12.0.0, current version 12.0.0)
        @executable_path/../lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.6)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Applications/Inkscape.app/Contents/Resources/lib/libtiff.3.dylib (architecture i386):
        @executable_path/../lib/libz.1.dylib (compatibility version 13.0.0, current version 13.5.0)
        @executable_path/../lib/libjpeg.8.dylib (compatibility version 12.0.0, current version 12.0.0)
        @executable_path/../lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.6)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Applications/MATLAB/MATLAB_Compiler_Runtime/v82/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/Applications/MATLAB/MATLAB_Compiler_Runtime/v84/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/Applications/MATLAB_R2015b.app/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/Applications/TeX/TeXworks.app/Contents/MacOS/libtiff.5.dylib:
        @executable_path/../MacOS/libtiff.5.dylib (compatibility version 8.0.0, current version 8.0.0)
        @executable_path/../MacOS/liblzma.5.dylib (compatibility version 6.0.0, current version 6.4.0)
        @executable_path/../MacOS/libjbig.2.dylib (compatibility version 0.0.0, current version 0.0.0)
        @executable_path/../MacOS/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
        @executable_path/../MacOS/libz.1.dylib (compatibility version 1.0.0, current version 1.2.7)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
        @executable_path/../MacOS/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libtiff.5.dylib:
        /Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.0.0)
        /Library/Frameworks/Mono.framework/Versions/3.4.0/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.4.0)
        /Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libjpeg.8.dylib (compatibility version 9.0.0, current version 9.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libtiff.5.dylib.dSYM/Contents/Resources/DWARF/libtiff.5.dylib:
/Users/jmollink/.Trash/HistoloZee-v03/HistoloZee.app/Contents/Frameworks/libtiff.5.dylib:
        @executable_path/../Frameworks/libtiff.5.dylib (compatibility version 8.0.0, current version 8.0.0)
        @executable_path/../Frameworks/liblzma.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        @executable_path/../Frameworks/libjpeg.9.dylib (compatibility version 10.0.0, current version 10.0.0)
        @executable_path/../Frameworks/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
/Users/jmollink/.Trash/MATLAB_R2014b.app/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
/Users/jmollink/anaconda/lib/libtiff.5.dylib:
        libtiff.5.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Users/jmollink/anaconda/pkgs/libtiff-4.0.2-0/lib/libtiff.5.dylib:
        /opt/anaconda1anaconda2anaconda3/lib/libtiff.5.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Users/jmollink/anaconda/pkgs/libtiff-4.0.2-1/lib/libtiff.5.dylib:
        libtiff.5.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/local/Cellar/libtiff/4.0.6/lib/libtiff.5.dylib:
        /usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
        /usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/usr/local/Cellar/openslide/3.4.1_1/libtiff/libtiff/.libs/libtiff.5.dylib:
        /usr/local/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
        /usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
        /usr/local/opt/jpeg/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
/usr/local/lib/libtiff.5.dylib:
        /usr/local/lib/libtiff.5.dylib (compatibility version 8.0.0, current version 8.4.0)
        /usr/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.3.0)
        /usr/local/opt/jpeg/lib/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libtiff.5.dylib.dSYM/Contents/Resources/DWARF/libtiff.5.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Library/Frameworks/Mono.framework/Versions/3.4.0/lib/libtiff.5.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Users/jmollink/anaconda/lib/libtiff.5.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Users/jmollink/anaconda/pkgs/libtiff-4.0.2-0/lib/libtiff.5.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Users/jmollink/anaconda/pkgs/libtiff-4.0.2-1/lib/libtiff.5.dylib (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Volumes/MobileBackups/Backups.backupdb/JeroenMMBPr/2015-11-14-132349/Macintosh HD/Applications/Gimp.app/Contents/Resources/lib/libtiff.3.dylib (No such file or directory)```
``````

**Comment by bgilbert** [comment] 2015-11-16 21:07
Yep, it's Matlab's copy:

```
/Applications/MATLAB/MATLAB_Compiler_Runtime/v82/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
/Applications/MATLAB/MATLAB_Compiler_Runtime/v84/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
/Applications/MATLAB_R2015b.app/bin/maci64/libtiff.5.dylib:
        @rpath/libtiff.5.dylib (compatibility version 6.0.0, current version 6.5.0)
```

Does it work if you run Matlab with the `DYLD_VERSIONED_LIBRARY_PATH` environment variable set to `/usr/local/opt/libtiff/lib`?  (And please verify that that directory exists.)

**Comment by jmollink** [comment] 2015-11-17 13:18
Unfortunately, I get the same error. 

```
Error using loadlibrary
There was an error loading the library
"/usr/local/opt/openslide/lib/libopenslide.0.dylib"
dlopen(/usr/local/opt/openslide/lib/libopenslide.0.dylib, 6): Library not loaded:
/usr/local/lib/libtiff.5.dylib
  Referenced from: /usr/local/opt/openslide/lib/libopenslide.0.dylib
  Reason: Incompatible library version: libopenslide.0.dylib requires version 8.0.0 or
  later, but libtiff.5.dylib provides version 6.0.0

Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...

Caused by:
    Error using loaddefinedlibrary
    dlopen(/usr/local/opt/openslide/lib/libopenslide.0.dylib, 6): Library not loaded:
    /usr/local/lib/libtiff.5.dylib
      Referenced from: /usr/local/opt/openslide/lib/libopenslide.0.dylib
      Reason: Incompatible library version: libopenslide.0.dylib requires version
      8.0.0 or later, but libtiff.5.dylib provides version 6.0.0
```

The folder `/usr/local/opt/libtiff/lib` indeed exists, has content and was set to the environment variable you specified.

**Comment by jmollink** [comment] 2015-11-18 17:30
I also tried adding the folder `/usr/local/opt/libtiff/lib` to the paths in the environmental variable `DYLD_LIBRARY_PATH` like this:

`
setenv('DYLD_LIBRARY_PATH',['/usr/local/opt/libtiff/lib/:' getenv('DYLD_LIBRARY_PATH')])
`

The library version error dissapeared this way, but a new one came in place.

```
>> openslide_load_library()
/var/folders/qm/j_jd0_vn3t9b8vxwslh4wtqr0000gq/T//mex_80110512818058_66752: line 2: 66825 Trace/BPT trap: 5       xcode-select -print-path > /var/folders/qm/j_jd0_vn3t9b8vxwslh4wtqr0000gq/T//mex_80110512841788_66752 2> /var/folders/qm/j_jd0_vn3t9b8vxwslh4wtqr0000gq/T//mex_80110512856440_66752
sh /var/folders/qm/j_jd0_vn3t9b8vxwslh4wtqr0000gq/T//mex_80110512818058_66752: Trace/breakpoint trap

Error using loadlibrary
Failed to preprocess the input file.
 Output from preprocessor is:/bin/bash: /xcrun: No such file or directory


Error in openslide_load_library (line 76)
loadlibrary(libName,'openslide-wrapper.h','alias','openslidelib',...
```

Any idea why its suddenly not seeing xcrun anymore?

**Comment by bgilbert** [comment] 2015-12-07 05:16
In the `DYLD_VERSIONED_LIBRARY_PATH` case, I wonder whether the variable was properly passed to Matlab.  Could you verify by calling `getenv` inside Matlab?

`DYLD_LIBRARY_PATH` should be roughly equivalent to `DYLD_VERSIONED_LIBRARY_PATH`.  It's possible in the second case that you're setting the variable too late: if you do it from inside Matlab, Matlab may have already loaded the older copy of libtiff beforehand.

On the other hand, the SIGTRAP from `xcode-select` shouldn't be happening.  It's possible that the two copies of libtiff really are binary-incompatible for some reason, but I don't know why that would cause the errors you're seeing.  If you can verify that either of the variables is properly set when Matlab starts, and you're still seeing odd crashes like the one above, then I'm out of ideas for now.

**Comment by fordanic** [comment] 2016-02-16 20:26
Given the lack of recent activity and that the issue appear to not be caused by the code but rather some specific libraries that are linked in MATLAB I close this issue. Reopen if you don't agree.

**Closed as completed by fordanic** 2016-02-16 20:26 UTC
