### ISSUE TITLE
when I make the openslide, I got bugs related to libtiff 

### ISSUE THREAD

**Issue by brisker** [fordanic/openslide-matlab#5] opened 2016-08-05 12:34 UTC
> # How to build?
> 
> ./configure
> make
> make install
> 
> (If building from the Git repository, you will first need to install
> autoconf, automake, libtool, and pkg-config and run "autoreconf -i".)

I follow the steps in https://github.com/uclouvain/openjpeg/blob/master/INSTALL.md
and all went well when I run "make",
and the bugs read like this:

src/.libs/libopenslide.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFRGBAImageEnd@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFClientOpen@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFFileName@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFCurrentDirectory@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFIsCODECConfigured@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFComputeTile@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFRGBAImageGet@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFSetDirectory@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFGetFieldDefaulted@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFRGBAImageBegin@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFClose@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to `TIFFReadRawTile@LIBTIFF_4.0'
src/.libs/libopenslide.so: undefined reference to`TIFFReadDirectory@LIBTIFF_4.0'

I have successfully build openslide previously(without opencv), but today I reinstall my ubuntu system and cmake the opencv with libtiff on(cmake -D BUILD_TIFF=ON ..) .So is the error cause by this? If so, could you please tell me how to fix this?(I have tried to cmake the openjpeg with libtiff on, but error again)

**Comment by fordanic** [comment] 2016-08-07 18:59
Hi @brisker,

It appears as the logged item here is a duplicate of an [issue](https://github.com/openslide/openslide/issues/180) logged at openslide. And as noted there, support issues are better handled by the openslide mailing list.

**Closed as completed by fordanic** 2016-08-07 18:59 UTC
